# Generated by Django 4.0.2 on 2022-02-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, verbose_name='Детали заказа')),
                ('customer_id', models.IntegerField(verbose_name='Клиент №')),
            ],
        ),
    ]
